### ISSUE TITLE
Nested arrays of domain types use wrong typecast

### ISSUE THREAD

**Issue by msand** [graphile/crystal#1722]
### Summary

Nested arrays of domain types use wrong typecast for inner domain array.

Thanks for your great work on Postgraphile, after several years of use, this is the first bug/inconvenience I've hit upon.

### Steps to reproduce

```sql
CREATE TYPE work_hour_parts AS
(
    from_hours   smallint,
    from_minutes smallint,
    to_hours     smallint,
    to_minutes   smallint
);

CREATE DOMAIN work_hour AS work_hour_parts
    NOT NULL CHECK (
            (VALUE).from_hours < 24 AND (VALUE).from_minutes < 60 AND
            ((VALUE).to_hours < 24 AND (VALUE).to_minutes < 60 OR
             (VALUE).to_hours = 24 AND (VALUE).to_minutes = 0) AND
            (VALUE).from_hours >= 0 AND (VALUE).from_minutes >= 0 AND (VALUE).to_hours >= 0 AND
            (VALUE).to_minutes >= 0 AND
            ((VALUE).from_hours < (VALUE).to_hours OR (VALUE).from_minutes < (VALUE).to_minutes)
    );

create or replace function check_work_hours(wh work_hour[])
    returns bool
    strict
    immutable
    language plpgsql
as
$body$
declare
    prev    work_hour_parts;
    current work_hour_parts;
begin
    foreach current in array wh
        loop
            if (prev is null) then
                prev := current;
            else
                if current.from_hours < prev.to_hours or
                   (current.from_hours = prev.to_hours and current.from_minutes <= prev.to_minutes) then
                    return false;
                end if;
            end if;
        end loop;
    return true;
end;
$body$;

CREATE DOMAIN workhours AS work_hour[] NOT NULL CHECK (check_work_hours(VALUE::work_hour[]));

CREATE DOMAIN working_hours AS workhours[] CHECK (cardinality(VALUE) = 8);

COMMENT ON DOMAIN working_hours IS 'Mo, Tu, We, Th, Fr, Sa, Su, Ho';

CREATE TABLE t
(
    k serial primary key,
    v working_hours
);
```

```graphql
mutation createT($input: CreateTInput!) {
  createT(input: $input) {
    t {
      k
      v {
        fromHours
        fromMinutes
        toHours
        toMinutes
      }
    }
  }
}
```

```json
{
  "input": {
    "t": {
      "v": [
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        []
      ]
    }
  }
}
```

```sh
npx postgraphile -c minimal_repro   --subscriptions  --dynamic-json   --no-setof-functions-contain-nulls   --no-ignore-rbac   --show-errostack=json   --extended-errors hint,detail,errcode   --export-schema-graphql schema.graphql   --graphiql "/"   --enhance-graphiql   --allow-explain   --enable-query-batching   --legacy-relations omit
```

### Expected results

Successful insertion

### Actual results

```json
{
  "errors": [
    {
      "errcode": "42846",
      "extensions": {
        "exception": {
          "errcode": "42846"
        }
      },
      "message": "cannot cast type work_hour[] to workhours[]",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createT"
      ],
      "stack": [
        "error: cannot cast type work_hour[] to workhours[]",
        "    at Parser.parseErrorMessage (/Users/msand/.npm/_npx/1b80421a9ae535da/node_modules/pg-protocol/dist/parser.js:287:98)",
        "    at Parser.handlePacket (/Users/msand/.npm/_npx/1b80421a9ae535da/node_modules/pg-protocol/dist/parser.js:126:29)",
        "    at Parser.parse (/Users/msand/.npm/_npx/1b80421a9ae535da/node_modules/pg-protocol/dist/parser.js:39:38)",
        "    at Socket.<anonymous> (/Users/msand/.npm/_npx/1b80421a9ae535da/node_modules/pg-protocol/dist/index.js:11:42)",
        "    at Socket.emit (node:events:520:28)",
        "    at addChunk (node:internal/streams/readable:315:12)",
        "    at readableAddChunk (node:internal/streams/readable:289:9)",
        "    at Socket.Readable.push (node:internal/streams/readable:228:10)",
        "    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
      ]
    }
  ],
  "data": {
    "createT": null
  }
}
```

### Additional context

Postgraphile produces this query:
```sql
with __local_0__ as (
    insert into "public"."t" ("v")
        values (array [
            array []::"public"."_work_hour",
            array []::"public"."_work_hour",
            array []::"public"."_work_hour",
            array []::"public"."_work_hour",
            array []::"public"."_work_hour",
            array []::"public"."_work_hour",
            array []::"public"."_work_hour",
            array []::"public"."_work_hour"
            ]::"public"."_workhours")
        returning *)
select (
           (
               case
                   when __local_0__ is null
                       then null
                   else __local_0__
                   end
               )
           )::text
from __local_0__;
```

While this query succeeds:

```sql
with __local_0__ as (
    insert into "public"."t" ("v")
        values (array [
            array []::workhours,
            array []::workhours,
            array []::workhours,
            array []::workhours,
            array []::workhours,
            array []::workhours,
            array []::workhours,
            array []::workhours
            ]::"public"."_workhours")
        returning *)
select (
           (
               case
                   when __local_0__ is null
                       then null
                   else __local_0__
                   end
               )
           )::text
from __local_0__;
````

### Possible Solution

Haven't found any workaround yet

**Comment by msand** [comment]
Seems that creating a type for the inner array makes insertions work, but instead select/query returns null for all the values:

```
CREATE TYPE workhours_inner AS (workhours work_hour[]);
CREATE DOMAIN workhours AS workhours_inner CHECK (check_work_hours((VALUE).workhours::work_hour[]));
```

**Comment by msand** [comment]
Seems using plain types, and putting the check on the column instead, works correctly.

```sql
CREATE TYPE work_hour_parts AS
(
    from_hours   smallint,
    from_minutes smallint,
    to_hours     smallint,
    to_minutes   smallint
);

create or replace function check_work_hour_parts(whp work_hour_parts)
    returns bool
    strict
    immutable
    language plpgsql
as
$body$
begin
    return whp.from_hours is not null AND
           whp.from_minutes is not null AND
           whp.to_hours is not null AND
           whp.to_minutes is not null AND
           whp.from_hours < 24 AND whp.from_minutes < 60 AND
           ((whp.to_hours < 24 AND whp.to_minutes < 60) OR (whp.to_hours = 24 AND whp.to_minutes = 0)) AND
           whp.from_hours >= 0 AND
           whp.from_minutes >= 0 AND
           whp.to_hours >= 0 AND
           ((whp.to_hours > 0 AND whp.to_minutes >= 0) OR (whp.to_hours = 0 AND whp.to_minutes > 0)) AND
           (whp.from_hours < whp.to_hours OR (whp.from_hours = whp.to_hours AND whp.from_minutes < whp.to_minutes));
end;
$body$;

create or replace function check_work_hours(wh work_hour_parts[])
    returns bool
    strict
    immutable
    language plpgsql
as
$body$
declare
    prev    work_hour_parts;
    current work_hour_parts;
begin
    foreach current in array wh
        loop
            if current is null then
                return false;
            end if;
            if not check_work_hour_parts(current) then
                return false;
            end if;
            if (prev is null) then
                prev := current;
            else
                if current.from_hours < prev.to_hours or
                   (current.from_hours = prev.to_hours and current.from_minutes <= prev.to_minutes) then
                    return false;
                end if;
            end if;
        end loop;
    return true;
end;
$body$;

CREATE TYPE workhours AS
(
    workhours work_hour_parts[]
);


create or replace function check_workhours(wh workhours[])
    returns bool
    strict
    immutable
    language plpgsql
as
$body$
declare
    current workhours;
begin
    foreach current in array wh
        loop
            if not check_work_hours(current.workhours) then
                return false;
            end if;
        end loop;
    return true;
end;
$body$;

CREATE TABLE t
(
    k serial primary key,
    v workhours[][] check (cardinality((v)) = 8 and check_workhours((v)))
);

COMMENT ON COLUMN t.v IS 'Mo, Tu, We, Th, Fr, Sa, Su, Ho';

insert into t(v)
values (array [
    row (array [row (0, 0, 1, 0)::work_hour_parts, row (1, 1, 1, 3)::work_hour_parts]::work_hour_parts[])::workhours,
    row (array [row (0, 0, 1, 0)::work_hour_parts]::work_hour_parts[])::workhours,
    row (NULL)::workhours,
    row (NULL)::workhours,
    row (NULL)::workhours,
    row (NULL)::workhours,
    row (NULL)::workhours,
    row (NULL)::workhours
    ]::workhours[]);

select *
from t;
```

```graphql
mutation createT($input: CreateTInput!) {
  createT(input: $input) {
    t {
      k
      v {
        workhours {
          fromHours
          fromMinutes
          toHours
          toMinutes
        }
      }
    }
  }
}
```

```json
{
  "input": {
    "t": {
      "v": [
          {
            "workhours": [
              {
                "fromHours": 0,
                "fromMinutes": 0,
                "toHours": 1,
                "toMinutes": 0
              }
          	]
          },
        [],
        [],
        [],
        [],
        [],
        [],
        []
      ]
    }
  }
}
```

```json
{
  "data": {
    "createT": {
      "t": {
        "k": 2,
        "v": [
          {
            "workhours": [
              {
                "fromHours": 0,
                "fromMinutes": 0,
                "toHours": 1,
                "toMinutes": 0
              }
            ]
          },
          {
            "workhours": null
          },
          {
            "workhours": null
          },
          {
            "workhours": null
          },
          {
            "workhours": null
          },
          {
            "workhours": null
          },
          {
            "workhours": null
          },
          {
            "workhours": null
          }
        ]
      }
    }
  }
}
```

**Comment by benjie** [comment]
Arrays are one of the things I dislike the most in PostgreSQL... and you're nesting them!

Nonetheless, thank you for the reproduction - I've addressed this bug in Version 5 and the fix will go out with the next release (V5 is in private alpha and available to sponsors only).

I do not plan to address this in V4... I'm not even sure where I'd begin 😅

**Comment by benjie** [comment]
Added very thorough test case for this kind of thing earlier: #1771
