### ISSUE TITLE
Grafserv imports Ruru which breaks bundling

### ISSUE THREAD

**Issue by innermatrix** [graphile/crystal#1775]
1. I am deploying to AWS lambda, which involves bundling
2. `grafserv` imports `ruru` 
3. `ruru` does all kinds of bundler-incompatible things like trying to `readFileSync` `package.json` etc

The stack looks like

```
Error: ENOENT: no such file or directory, open '/var/package.json'
    at Object.openSync (node:fs:603:3)
    at readFileSync (node:fs:471:35)
    at mapIterator (/node_modules/ruru/src/server.ts:7:3)
    at file:///var/task/pglambda-v2.mjs:9:495
    at getGrafservHooks (/node_modules/grafserv/src/middleware/graphiql.ts:2:1)
    at file:///var/task/pglambda-v2.mjs:9:495
    at optionsFromConfig (/node_modules/grafserv/src/core/base.ts:22:1)
    at file:///var/task/pglambda-v2.mjs:9:495
    at <anonymous> (/node_modules/grafserv/src/index.ts:1:1)
    at file:///var/task/pglambda-v2.mjs:9:495
```

As a first pass, I suggest making `ruru` lazily evaluate non-bundleable code so that it can be imported in bundled contexts without error.

**Comment by benjie** [comment]
Also: https://github.com/graphile/crystal/blob/7d5a40fa581e307ef48b51b18185355f0d49f3de/grafast/ruru/src/server.ts#L11 which seems to cause issues with Nuxt bundling.

**Comment by benjie** [comment]
We actually have a "version" script that we use to keep the versions in sync without requiring a read of package.json, so should be trivial to expand that to this package.json read; see:

https://github.com/graphile/crystal/blob/main/grafast/grafast/src/version.ts

Fixing the above read of ruru.min.js is going to be a different thing; but I think we can just use something like this to inline it into JS instead of reading from file:

https://github.com/graphile/worker/blob/aae7527fe4a2e3464bb2f198a228c4219ffc6cd9/scripts/buildSqlModule.js#L10-L22

**Comment by psirenny** [comment]
Darn, just hit this one as well when deploying to Vercel which, uses AWS Lambda.

**Comment by zarybnicky** [comment]
I'm almost done with my v5 migration, but this is a dealbreaker for me.

The usual workaround from v4 that used to work for worker migrations etc. is broken: `fs.copyFileSync(require.resolve('ruru/bundle/ruru.min.js'), 'bundle/ruru.min.js');`

Adding the bundle to exports in `ruru/package.json` would be a viable low-effort workaround, namely just adding `"./bundle/ruru.min.js": "./bundle/ruru.min.js"` to this object:

https://github.com/graphile/crystal/blob/6fa82ed4595ec45559e3807a9a0f4031c3789a3b/grafast/ruru/package.json#L9-L24


(For the reference, this is the (very basic) script that's served me very well so far for v4.)

```js
const esbuild = require('esbuild');
const fs = require('node:fs');
const childProcess = require('node:child_process');

(async () => {
  await esbuild.build({
    entryPoints: ['./src/index.ts'],
    bundle: true,
    platform: "node",
    external: ["pg-cloudflare", "pg-native", "uglify-js"],
    outdir: './dist',
  })
  fs.renameSync("dist/index.js", "dist/index.cjs");
  childProcess.execSync("sed -i s@/../sql@/sql@g dist/index.cjs")
  childProcess.execSync("sed -i s@../../res/@./@ dist/index.cjs")

  fs.copyFileSync(require.resolve('graphile-build-pg/res/watch-fixtures.sql'), 'dist/watch-fixtures.sql');
})()
```
