### ISSUE TITLE
Expected nullableType to be a list or abstract type, instead found ...

### ISSUE THREAD

**Issue by devunt** [graphile/crystal#1976]
### Summary

When running query `Expected nullableType to be a list or abstract type, instead found ...` error occurs.

### Steps to reproduce

Minimal schema
```graphql
interface UserNotification {
  id: ID!
}

type Query {
  notifications: [UserNotification!]!
}
```

Minimal query
```graphql
query {
  notifications {
    id
  }
}
```

### Expected results

It runs.

### Actual results

```
Error: Query planning error: GrafastInternalError<0a293e88-0f38-43f6-9179-f3ef9a720872>: Expected nullableType to be a list or abstract type, instead found UserNotification!
    at OperationPlan.planOperation (/Users/finn/workspaces/penxle/node_modules/.pnpm/grafast@0.1.1-beta.6_@envelop+core@5.0.0_graphql@16.8.1_tamedevil@0.0.0-beta.6/node_modules/grafast/dist/engine/OperationPlan.js:375:19)
    at new OperationPlan (/Users/finn/workspaces/penxle/node_modules/.pnpm/grafast@0.1.1-beta.6_@envelop+core@5.0.0_graphql@16.8.1_tamedevil@0.0.0-beta.6/node_modules/grafast/dist/engine/OperationPlan.js:185:14)
    at establishOperationPlan (/Users/finn/workspaces/penxle/node_modules/.pnpm/grafast@0.1.1-beta.6_@envelop+core@5.0.0_graphql@16.8.1_tamedevil@0.0.0-beta.6/node_modules/grafast/dist/establishOperationPlan.js:141:25)
    at grafastPrepare (/Users/finn/workspaces/penxle/node_modules/.pnpm/grafast@0.1.1-beta.6_@envelop+core@5.0.0_graphql@16.8.1_tamedevil@0.0.0-beta.6/node_modules/grafast/dist/prepare.js:364:80)
    at withGrafastArgs (/Users/finn/workspaces/penxle/node_modules/.pnpm/grafast@0.1.1-beta.6_@envelop+core@5.0.0_graphql@16.8.1_tamedevil@0.0.0-beta.6/node_modules/grafast/dist/execute.js:55:55)
    at execute (/Users/finn/workspaces/penxle/node_modules/.pnpm/grafast@0.1.1-beta.6_@envelop+core@5.0.0_graphql@16.8.1_tamedevil@0.0.0-beta.6/node_modules/grafast/dist/execute.js:77:12)
    at /Users/finn/workspaces/penxle/node_modules/.pnpm/grafast@0.1.1-beta.6_@envelop+core@5.0.0_graphql@16.8.1_tamedevil@0.0.0-beta.6/node_modules/grafast/dist/envelop.js:36:66
```

### Additional context

```
grafast 0.1.1-beta.6
```

### Possible Solution
If I change https://github.com/graphile/crystal/blob/6e367b652a882c404b2e273a56645580da2bc1e0/grafast/grafast/src/steps/graphqlResolver.ts#L227 into following lines, it works well.

```ts
if (isAbstractType(nullableType)) {
    this.abstractType = nullableType;
} else {
    this.abstractType = nullableType.ofType;
}
```
Not sure if this is a correct way to solve it, though.

**Comment by benjie** [comment]
Hmmm... The issue is that `nullableType` is in fact a non-nullable type; the bug exists somewhere else. As a short term solution, consider changing `notifications: [UserNotification!]!` to `notifications: [UserNotification]!`; making the inner value non-nullable later is a non-breaking change.

**Comment by benjie** [comment]
Please could you provide a fully working `.mjs` file that constructs the schema and issues the query demonstrating the issue please?

**Comment by benjie** [comment]
I was unable to reproduce this; I created a test file using the code you provided but alas, no luck.
