### ISSUE TITLE
Confusing errors when referencing wrong type name in makeExtendSchemaPlugin

### ISSUE THREAD

**Issue by p-bakker** [graphile/crystal#2217]
### Summary

If referencing a non-existing type in a makeExtendSchemaPlugin plugin that targets just one entity, this results in a cascade of exceptions on every subsequent entity

### Steps to reproduce

See https://discord.com/channels/489127045289476126/1296863704364879902/1297218564876406947

### Expected results

Only 1 exception on the affected entities

### Actual results

Exceptions on all subsequent entities

### Additional context
\
(https://discord.com/channels/489127045289476126/1296863704364879902/1297218564876406947)

**Comment by benjie** [comment]
(Reminder to self: the issue was referencing `Metadata` when the type name was `Metadatum`. Caused extend plugin to blow up the entire `Query` type, which then went on to blow up mutation payload types.)

**Comment by benjie** [comment]
```ts
    extendSchema({
      typeDefs: /* GraphQL */ `
        extend type Query {
          test2217: NonExistentType
        }
      `,
    }, 'MyExtendSchemaPlugin'),
```

Now fails to build the schema with:

```
Error occurred during watch schema generation: Error: MyExtendSchemaPlugin could not find type named 'NonExistentType'.
    at getType (/home/benjie/Dev/graphile/crystal/graphile-build/graphile-utils/src/makeExtendSchemaPlugin.ts:1169:15)
    at /home/benjie/Dev/graphile/crystal/graphile-build/graphile-utils/src/makeExtendSchemaPlugin.ts:1347:24
    [...]
```
